branch-defaults:
  master:
    environment: Udagramserver4-env
environment-defaults:
  Udagramserver3-env:
    branch: null
    repository: null
global:
  application_name: udagram-server-4
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
