branch-defaults:
  default:
    environment: Udagramserver1-env
global:
  application_name: udagram-server-1
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1f
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb_cli
  repository: null
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip
